### ISSUE TITLE
Error: Os { code: 28, kind: InvalidInput, message: "Invalid argument" }

### ISSUE THREAD

**Issue by rotk2022** [WasmEdge/wasmedge-async#2]
I got an error when runninng the demo examples/async_tcp_server.And I try to debug by CodeLLDB ,and it didn't work.
![1655719129946](https://user-images.githubusercontent.com/105830845/174577561-2b8fa97a-5043-4d91-a0bf-3ee9a32cf7de.png)
How to debug it?

**Comment by rotk2022** [comment]
The error seems to be related to the version of wasmedge_wasi_socket. it works normally here:https://github.com/abhinandanudupa/wasmedge_wasi_socket.git. I got the same error when running the http_server example from here:https://github.com/second-state/wasmedge_wasi_socket.git

**Comment by MediosZ** [comment]
Hi, this may be caused by a mismatched version of WasmEdge.
Please try the latest version of WasmEdge (0.10.0).

**Comment by rotk2022** [comment]
> Hi, this may be caused by a mismatched version of WasmEdge. Please try the latest version of WasmEdge (0.10.0).

yes,that is right
